<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="griffon.exceptions.NewInstanceExceptionSpec" tests="2" skipped="0" failures="0" errors="0" timestamp="2017-05-06T14:34:17" hostname="testing-docker-61402520-d4dd-4f1f-ac93-0a4d284e0ebf" time="0.006">
  <properties/>
  <testcase name="Exception should have proper formatted message[0]" classname="griffon.exceptions.NewInstanceExceptionSpec" time="0.005"/>
  <testcase name="Exception should have proper formatted message[1]" classname="griffon.exceptions.NewInstanceExceptionSpec" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
