<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="griffon.exceptions.NewInstanceExceptionSpec" tests="2" skipped="0" failures="0" errors="0" timestamp="2017-05-02T08:34:11" hostname="testing-docker-f5468bb5-c282-4c60-9f7e-ab0b1a158756" time="0.012">
  <properties/>
  <testcase name="Exception should have proper formatted message[0]" classname="griffon.exceptions.NewInstanceExceptionSpec" time="0.011"/>
  <testcase name="Exception should have proper formatted message[1]" classname="griffon.exceptions.NewInstanceExceptionSpec" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
